  services:
    app:
      build: .
      ports:
        - "8000:80"
        - "5173:5173"
      volumes:
        - .:/var/www/html
      command: sh -c "docker-php-entrypoint apache2-foreground" 
      develop:
        watch:
          - action: sync
            path: .
            target: /var/www/html
            ignore:
            - vendor/
            - .git/
            - node_modules/
          - action: rebuild
            path: composer.json
      env_file:
        - .env