  services:
    app:
      build: .
      ports:
        - "8000:80"
        - "5173:5173"
      volumes:
        - .:/var/www/html
      command: sh -c "npm install && npm run dev & docker-php-entrypoint apache2-foreground" 
      develop:
        watch:
          - action: sync
            path: .
            target: /var/www/html
            ignore:
            - vendor/
            - .git/
            - node_modules/
          - action: rebuild
            path: composer.json
      depends_on:
        - db
      env_file:
        - .env

    db:
      image: mysql:8.0
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: seb
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql

  volumes:
    db_data:


# para executar comandos php via container 
# docker compose exec app
# ex: docker compose exec app  php artisan migrate